### ISSUE TITLE
FATAL EXCEPTION error after attempting to modify

### ISSUE THREAD

**Issue by adetheprince** [coderJohnZhang/TvLauncher#2]
Hi there
I really like your launcher so I download it to test it.
Its working but after I try to edit and remove Home menu or any menu I get this fatl error.
Can you tell me how to solve this please and how to remove all boxes in main screen, I want horizontal views without home button, setting, app buttons.
Many thanks.

> D/AppOperationReceiver: ============创建广播接收器===================owner---com.gotech.tv.launcher.activity.MainActivity@b11d944
I/art: Background partial concurrent mark sweep GC freed 55(2496B) AllocSpace objects, 0(0B) LOS objects, 39% free, 3MB/6MB, paused 1.088ms total 102.675ms
D/AndroidRuntime: Shutting down VM

                  --------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.gotech.tv.launcher, PID: 2382
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.gotech.tv.launcher/com.gotech.tv.launcher.activity.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                      at android.app.ActivityThread.-wrap11(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                   Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
                      at com.gotech.tv.launcher.view.ReflectView.createCutReflectedImage(ReflectView.java:74)
                      at com.gotech.tv.launcher.view.ReflectView.reflectImage(ReflectView.java:108)
                      at com.gotech.tv.launcher.page.PageHome.reflectImageView(PageHome.java:70)
                      at com.gotech.tv.launcher.page.PageHome.initView(PageHome.java:57)
                      at com.gotech.tv.launcher.page.PageHome.<init>(PageHome.java:35)
                      at com.gotech.tv.launcher.activity.MainActivity.initView(MainActivity.java:95)
                      at com.gotech.tv.launcher.activity.MainActivity.onCreate(MainActivity.java:45)
                      at android.app.Activity.performCreate(Activity.java:6237)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                      at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:148) 
                      at android.app.ActivityThread.main(ActivityThread.java:5417) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by coderJohnZhang** [comment]
As the log say NullPointerException, easy ways is to try{} catch{} it where the error happens. Better ways, if you try to edit the UI, at the same time, modify the business logic. createCutReflectedImage(Bitmap bitmap, int cutHeight) method in ReflectView class, the first argument bitmap should not be null, you know. However, this kind of common exception just need to debug several times.
